on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    name: Delete old tags
    steps:
      - name: Run checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
      - name: Delete tags
        run: |
          git show-ref --tag | awk '{print ":" $2}' | sort -nr | tail -n +2 | xargs git push origin
